/* Generated by Yosys 0.64 (git sha1 6d2c445ae-dirty, g++ 15.2.1 -march=native -O3 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -mpclmul -ffile-prefix-map=/startdir/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

(* hdlname = "retro_v_top" *)
(* top =  1  *)
(* src = "src/retro_v_top.sv:1.1-34.10" *)
module retro_v_top(instruction);
  (* src = "src/retro_v_top.sv:2.24-2.35" *)
  input [31:0] instruction;
  wire [31:0] instruction;
  (* src = "src/retro_v_top.sv:12.20-12.29" *)
  wire [7:0] immediate;
  (* src = "src/retro_v_top.sv:13.20-13.24" *)
  wire [7:0] load;
  (* src = "src/retro_v_top.sv:11.20-11.28" *)
  wire [7:0] register;
  (* src = "src/retro_v_top.sv:14.20-14.25" *)
  wire [7:0] store;
  assign register = 8'h33;
  assign immediate = 8'h13;
  assign load = 8'h03;
  assign store = 8'h23;
endmodule
